Разметка главной страницы
htmlacademy-adaptive/2011595-cat-energy-25 pull request #2
Opened 2022-04-01 15:08 UTC by slava560730

---
:mortar_board: [Разметка главной страницы](https://up.htmlacademy.ru/adaptive/25/user/2011595/tasks/2)

2022-04-04 12:28 UTC, Manyaka requested changes

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        <header class="offer__header">
оптимальнее не использовать тут тег хедер

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        <span class="visually-hidden">Открыть меню</span>
точки в вижуали-хидден, по аналогии с альтами

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +      <button class="main-nav__toggle" type="button">
проверь у всех кнопок типы

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +      <img class="main-header__logo-image" src="img\logos\mobile-logo.svg" width="191" height="37.6"
не надо дробные размеры

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        alt="Логотип Cat Energy из картинки и подписи.">
не удобно картинку и подпись держать в одном лого. Есть варианты почему так?

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +      <div class="main-nav__wrapper">
див лишний. Как всегда все дивы, пока ты не начал делать цсс и не понял, где тебе нужны буду врапперы - лишние. Как пример из реальной жизни: ты замечал, что все пенсионеры кладут паспорт в пакет, потом ещё в один пакет и потом в сумку? Вот два пакета не надо. Ул - прекрасный тег и может стилизоваться.

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +      <div class="offer__wrapper">
Больше дивов богу дивов :) Секшен один не достаточно обёртычный? :)

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +      <div class="offer__wrapper">
убери все дивы врапперы из секшенов

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        <ul class="offer__list">
Самостоятельный блок

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        <ul class="work__list">
Самостоятельный блок.

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        <ul class="work__list">
Ул всегда самостоятельный блок

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +            <p class="work__description">Функциональное питание содержит только полезные питательные вещества.</p>
параграф избыточен, ли может содержать текст

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +            <div class="before-after__price">
Это же текст - какой тег у нас для обёртки текста?

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +          <div class="before-after__price-wrapper">
лишний враппер

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +            <div class="comparisons__image">
пятьсот миллионов врапперов

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +          <h2 class="contacts__title">Приглашаем <br>к сотрудничеству<br>дилеров!</h2>
Это не заголовок, потому что заголовок озаглавливает, а это просто текст

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +          <img class="contacts__map-pin" src="" alt="Точка на карте.">
ну img как фолбек, если карта не загрузилась интерактивная - норм. Только пин убери

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +      <a class="main-footer__logo">
Отлично, что ты везде не пишешь хрефы у ссылки, потому что мы на этой самой странице!

2022-04-04 12:28 UTC, Manyaka commented on source/index.html
> +        <a class="copyright__link-logo" href="http://htmlacademy.ru" aria-label="Переход на сайт HTML Academy.">
Отличный альт!

2022-04-11 05:46 UTC, Manyaka requested changes

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +      <span class="offer__intro">Занялся собой? займись котом!</span>
```suggestion
      <p class="offer__intro">Занялся собой? займись котом!</p>
```

почему `p` а не `span`?

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +      </a>
всё, тут закончился секшен оффер, дальше уже другая секция

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +        <li class="offer-list__item offer__item--slim">
```suggestion
        <li class="offer-list__item offer-list__item--slim">
```

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +        <li class="offer-list__item offer__item--slim">
и второй поправь тоже

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +          <span class="offer-list__description">Ваш кот весит больше собаки и почти утратил способность лазить по
когда выше ответишь про разницу между спаном и параграфом, то тут сразу заметишь как поправить

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +          <p class="work-list__text">Функциональное питание содержит только полезные питательные вещества.</p>
Ну вот тут правильно текст разметил параграфами!

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +        <span class="before-after__text">Борис сбросил 5 кг за 2 месяца, просто заменив свой обычный корм на Cat
комент, специально не пишу что тут не так, давай развивай глазомер

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +        <div class="before-after__price">
```suggestion
        <p class="before-after__price">
```

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +      <div class="before-after__half comparisons">
```suggestion
      <div class="before-after__half comparison">
```

единственное число, потому что тут только 1 сравнение

2022-04-11 05:46 UTC, Manyaka commented on source/index.html
> +        <span class="contacts__address">ул. Большая<br> Конюшенная, д. 19/8<br>Санкт-Петербург</span>
текст кладём в параграфы

2022-04-13 06:27 UTC, Manyaka requested changes

2022-04-13 06:27 UTC, Manyaka commented on source/index.html
> +            Пора на диету! Cat Energy Slim поможет вашему питомцу сбросить лишний вес.</p>
бьютифаить то надо, чего за кривота то

2022-04-13 06:27 UTC, Manyaka commented on source/index.html
> +        <li class="offer-content-list__item offer-list__item--slim">
```suggestion
        <li class="offer-content-list__item offer-content-list__item--slim">
```

ну как только ты переименовал ул, что можно было не делать, надо все элементы его переименовывать соответственно

2022-04-13 06:27 UTC, Manyaka commented on source/index.html
> +          <a class="offer-content-list__description-button offer-content-list__description-button--arrow" href="#">
А зачем тебе тут модификатор?

2022-04-13 06:27 UTC, Manyaka commented on source/form.html
> +        <li class="site-list__item site-list__item--active">
какой пункт меню активный?

2022-04-13 06:27 UTC, Manyaka commented on source/form.html
> +    <section class="contacts">
ну вот ты увидел, что уже на 2-й странице есть такой же блок внизу, который потом будет повторяться на всех других страницах. Есть идея засунуть его в футер. Как тебе?

2022-04-13 06:27 UTC, Manyaka commented on source/catalog.html
> +    <section class="container-catalog">
лишний варппер

2022-04-13 06:27 UTC, Manyaka commented on source/catalog.html
> +          <a class="catalog__order button" href="#">Заказать</a>
самостоятельный блок

2022-04-13 06:27 UTC, Manyaka commented on source/catalog.html
> +    <section class="container-catalog">
подумай, на какой ещё странице есть аналогичный враппер и он тоже лишний

2022-04-13 06:27 UTC, Manyaka commented on source/form.html
> +      <form class="form" action="https://echo.htmlacademy.ru/" method="get">
```suggestion
      <form class="form" action="https://echo.htmlacademy.ru/" method="post">
```

много данных, лучше постом отправлять

2022-04-13 06:27 UTC, Manyaka commented on source/form.html
> +      <form class="form" action="https://echo.htmlacademy.ru/" method="get">
супер, что сделал форму самостоятельным блоком!

2022-04-13 06:27 UTC, Manyaka commented on source/form.html
> +        <fieldset class="form__field-name-weight-age name-weight-age">
а вот это не самостоятельный блок, это всё элементы формы. Всегда все элементы формы (в html) элементы формы (по бему)

Слово элемент тут в двух значениях - на хтэмельском языке и в бем-понятиях

2022-04-14 04:34 UTC, Manyaka commented on source/form.html
> +        <li class="site-list__item site-list__item--active">
не поправил. Активный - форма, а у тебя каталог.

2022-04-14 04:36 UTC, Manyaka commented on source/catalog.html
> +    <section class="container-catalog">
всё ещё это лишние, абсолютно лишние врапперы на обоих страницах - каталоге и форме.

2022-04-14 04:36 UTC, Manyaka commented on source/catalog.html
> +    <section class="container-catalog">
почему тебя смущает положить всё в мейн? main - прекрасный тег, как раз для главного на странице.

2022-04-14 04:37 UTC, Manyaka commented on source/catalog.html
> +          <a class="catalog__order button" href="#">Заказать</a>
не сделано

2022-04-14 04:54 UTC, Manyaka requested changes

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +            <p class="form__text">Имя:*</p>
параграфы убрать, лейбл инлайновый элемент, а блоки в инлайны не пихают. Ну и текст обернуть лейблом - связать с инпутом через for

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +            <input class="form__input" type="text" placeholder="7" name="cat-weight" required>
какой тип инпута тут можно использовать?

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +            <input class="form__input" type="text" name="cat-age" placeholder="7">
тут тоже можно подумать про тип инпута

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +          <ul class="form__radio-button">
ul - самостоятельный блок :) - если чего, он не элемент формы

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +                <span class="form__control-mark"></span>
неее, давай не будет радио делать спанами, давай по-современней через appearance

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +            <input class="form__contact-input" type="tel" placeholder="8 (960) 900-60-90" name="phone-nomber"
вот тут супер сделал, и тип нужный использовал и даже паттерн добавил

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +                <span class="form__control-mark"></span>
чекбоксы аналогично радио

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +          <ul class="form__checkbox">
тоже самое, что у радио - ul

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +        <button class="form__button" type="submit"><span class="button__text">Отправить заявку</span></button>
Зачем спан внутри? убери, нет в нём смысла. Пятьсот миллионов врапперов :) Паспорт в пакете в пакете в пакете маячит перед тобой в старости :) Не надо так, ты будешь современный дед, только в одном зип-пакете паспорт носить.

2022-04-14 04:54 UTC, Manyaka commented on source/form.html
> +        <p class="form__required">* — Обязательные поля</p>
Да, тут параграф - всё правильно, это много текста и не лейбл.

2022-04-14 17:17 UTC, slava560730 commented on source/form.html
> +        <button class="form__button" type="submit"><span class="button__text">Отправить заявку</span></button>
ахахаха
ура, я буду дедом

2022-04-15 06:23 UTC, Manyaka requested changes

2022-04-15 06:23 UTC, Manyaka commented on source/catalog.html
> +          <div class="product-info">
лишний див

2022-04-15 06:23 UTC, Manyaka commented on source/catalog.html
> +            <table class="product-info__table description-table">
а это норм, что самостоятельный блок

2022-04-15 06:23 UTC, Manyaka commented on source/catalog.html
> +                <td class="description-table__cell">Масса</td>
```suggestion
                <th class="description-table__cell">Масса</th>
```

почему th?

2022-04-15 06:23 UTC, Manyaka commented on source/catalog.html
> +          </div>
этот блок совершенно аналогичен блоку `product-info`. Ну там выше ты див только уберешь, и как там поправишь, так и тут сделай.

2022-04-15 06:23 UTC, Manyaka commented on source/catalog.html
> +          <a class="show-all__order button" href="#">Показать еще</a>
Это кнопка `catalog-item__order`. Что ей надо добавить, чтобы ты её смог сделать серой?

2022-04-15 06:23 UTC, Manyaka commented on source/catalog.html
> +          <a class="additional-products-list__order button" href="#">Заказать</a>
Самостоятельный блок

2022-04-15 06:23 UTC, Manyaka commented on source/form.html
> +        <label class="form__weight" for="weight">
лейбл имени отличается от лейбла веса? Я тебе даже больше скажу, ни один лейбл в этой форме не отличается от другого. Никогда ни один лейбл в форме не отличается от друго лейбла в этой же форме. Единственное отличие: со звездочкой или без. 

Это какой полёт фантазии должен быть у дизайнера, чтобы он тебе нарисовал 13 разных лейблов, чтобы ты им дал 13 разных классов?!

2022-04-15 06:23 UTC, Manyaka commented on source/form.html
> +      <fieldset class="form__field-radio">
тоже самое с филдсетами

2022-04-15 06:23 UTC, Manyaka commented on source/form.html
> +          <li class="radio-button__weight-loss">
Опять: почему все лишки в этой улке имеют разный дизайн? Какой тогда смысл в улке, если в html в unorder list объединяются элементы как раз благодаря одинаковости?

2022-04-15 06:23 UTC, Manyaka commented on source/form.html
> +            </label>
неудачное название класса, не понятно, что это радио или чекбокс, надо что-нибудь дописать к классу: контрол - хорошее слово, но явно не хватает ещё слова, можно тупо: `radio-checkbox-control`

2022-04-15 06:23 UTC, Manyaka commented on source/form.html
> +        <label class="form__contact-nomber" for="nomber">
```suggestion
        <label class="form__contact-nomber" for="number">
```

nomber - нет такого слова

2022-04-15 06:23 UTC, Manyaka commented on source/form.html
> +        <textarea class="form__comment-text" placeholder="Расскажите обо всех повадках кота" name="comment"></textarea>
текст ареа без лейбла. И вообще убери филдсет на текст арию, бедненькая обернули её в пятьсот оберток, хотя она тут одна и смысла в этом нет.

Какое главное преимущество филдсета?

2022-04-15 14:39 UTC, slava560730 commented on source/form.html
> +        <label class="form__contact-nomber" for="nomber">
наступил второй раз на грабли

2022-04-16 04:57 UTC, Manyaka requested changes

2022-04-16 04:57 UTC, Manyaka commented on source/form.html
> +      <textarea class="form__comment-text" placeholder="Расскажите обо всех повадках кота" name="comment"></textarea>
Текст ареа хочет лейбл, как и все элемент формы - он ей нужен. Как мы делаем, когда на дизе лейбла не видно, а он нужен?

2022-04-16 04:57 UTC, Manyaka commented on source/form.html
> +        <input class="form__contact-input" type="tel" placeholder="8 (960) 900-60-90" name="phone-number"
Не это обычные форм-инпуты, потому что они по дизу не отличаются ничем от других форм инпутов. А икноки ты будешь добавлять через модификаторы. И, кстати, не к инпутам, потому что на инпуты ничего не навешать. Так что сейчас, пока ты не знаешь как будешь делать иконки - ничего не делай для этого.

2022-04-16 04:57 UTC, Manyaka commented on source/form.html
> +        <input class="form__contact-input" type="tel" placeholder="8 (960) 900-60-90" name="phone-number"
Всегда надо работать итерациями - сначала всё просто - одни теги, наименее возможное количество. Потом начинаешь добавлять классы по бему, начинаешь понимать немного где будет мод - например, по серой кнопке уже понятно, что там будет мод над зелёной. Потом начинаешь добавлять цсс - понимаешь, что некоторые классы надо переименовать, потом строишь сетку - надо добавить некоторые дивы-обёртки, потом раскидываешь декоративку - понимаешь, что надо добавить ещё обёртки, и так вот итерациями строишь проект. 

Через 10 лет, не раньше, не льсти ни себе, никому (в школе все учатся 10 лет, хоть убейся, никто раньше 10 не пройдёт). Так и тут, не надо себе же портить итерации и пытаться сразу всё засунуть в первую итерацию. Через 10 лет - да, засунешь, но не на 2-м проекте. 

Твоя сила будет в методичности. Я вот ещё на первом курсе заметила, что ты методично делаешь домашки. Очень дисциплинировано. Это твоя сила, надо её развивать, тк ты на ней сможешь выехать и преуспеть в профессии. Так и тут - просто методично и дисциплинировано строишь проект, не спешишь всё сразу сделать.

2022-04-16 04:57 UTC, Manyaka commented on source/form.html
> +        <input class="form__contact-input" type="tel" placeholder="8 (960) 900-60-90" name="phone-number"
Ну понятно, то ты как нормальный молодой студент должен послать авторитет и сказать, а я сделаю всё на 3-м проекте! В жопу 10 лет! Это чтобы ты не считал судьбой какой-то 10 лет, нет, всё в твоих руках, ты можешь и быстрее набраться опыта, конечно. И потом, кто знает, возможно, у тебя талант в вёрстке :)

Но методичность это прям твоё, смотри, ведь ты даже паттерн добавил, и во всех альтах точки расставил! (я методичности противопоставляю разгильдяйство).

2022-04-16 04:57 UTC, Manyaka commented on source/form.html
> +      <textarea class="form__comment-text" placeholder="Расскажите обо всех повадках кота" name="comment"></textarea>
И кстати, текст ареа тоже инпут, у неё весь диз абсолютно такой же, как у других инпутов в форме. Только высота больше. Какой приём из бема можно тут использовать?

2022-04-16 04:57 UTC, Manyaka commented on source/catalog.html
> +            <span class="additional-products-list-item__price">200 Р.</span>
```suggestion
            <p class="additional-products-list-item__count">
                <span class="additional-products-list-item__price">1 упаковка (100 г)</span>
                <span class="additional-products-list-item__price">200 Р.</span>
            </p>
```

2022-04-17 07:28 UTC, Manyaka requested changes

2022-04-17 07:28 UTC, Manyaka commented on source/form.html
> +            <label class="radio-checkbox-control">
```suggestion
            <label class="radio-control">
```

ну раз ты ниже назвал чекбоксы - чекбокс контролом, то тут тогда уже нет смысла называть это радио-чекбокс-контролом, потому что это класс не для двух контролов, а только для радио теперь остался.

2022-04-17 10:48 UTC, merged