Module3 task1
htmlacademy-adaptive/2011595-cat-energy-25 pull request #4
Opened 2022-04-17 14:06 UTC by slava560730

2022-04-21 12:48 UTC, Manyaka requested changes

2022-04-21 12:48 UTC, Manyaka commented on source/sass/global/fonts.scss
> +  src: url("../fonts/oswaldregular.woff2") format("woff2"),
```suggestion
  src: url("../../fonts/oswaldregular.woff2") format("woff2"),
```

2022-04-21 12:48 UTC, Manyaka commented on source/sass/global/global.scss
> +$Arial: "Arial", sans-serif;
А для Освальда чего не сделал переменную?

2022-04-21 12:48 UTC, Manyaka commented on source/sass/global/global.scss
> +$Arial: "Arial", sans-serif;
Вынеси это в файл, который называется `variables`

2022-04-21 12:48 UTC, Manyaka commented on source/sass/style.scss
> +@import "./global/fonts.scss";
```suggestion
@import "./global/fonts";
```

расширения не нужны, особенность саса, у лесс, наоборот, надо расширения файлов.
Когда удалишь расширения (через заменить делай, .scss заменить на пустоту), заново отсортируй по-алфавиту. Тут легко видеть как надо сортировать, тк у тебя файлы в проекте тоже отсортированы по-алфавиту

2022-04-21 20:18 UTC, slava560730 commented on source/sass/style.scss
> +@import "./global/fonts.scss";
классная фишка
я до этого через альт выделял строки и удалял

2022-04-25 12:12 UTC, Manyaka requested changes

2022-04-25 12:12 UTC, Manyaka commented on source/sass/blocks/before-after-list.scss
> +  font-family: "Arial", sans-serif;
ты же придумал переменную для этого семейства шрифта, так что нужно использовать

2022-04-25 12:12 UTC, Manyaka commented on source/sass/blocks/checkbox.scss
> +}
нет таких элементов

2022-04-25 12:12 UTC, Manyaka commented on source/sass/global/variables.scss
> +}
нет, в прошлом коменте было написано, что вынести в вариаблес, а что оставить в глобале. Помойку не надо устраивать. Переменные никогда не равны классам, у них классовая ненависть друг к другу. Переменные всегда лежат в своём файле, глобальные стили в своём.

2022-04-25 12:12 UTC, Manyaka commented on source/sass/blocks/before-after-list.scss
> +  margin-bottom: 20px;
марджин уже есть на 3 строке

2022-04-25 12:12 UTC, Manyaka commented on source/sass/blocks/gift.scss
> +    background-image: url("../img/background/gift-background-mobile.jpg");
```suggestion
    background-image: url("../../img/background/gift-background-mobile.jpg");
```

нужно поправить все урлы, не только фонты ушли вглубь же

2022-04-25 12:12 UTC, Manyaka commented on source/sass/blocks/gift.scss
> +    background-repeat: no-repeat;
бекграунд уже есть на 26 строке. Почитай, что входит в шорткат "бекграунд"

2022-04-25 12:12 UTC, Manyaka commented on source/sass/blocks/gift.scss
> +    background-repeat: no-repeat;
аналогично в offer

2022-04-26 06:34 UTC, merged